# Generated by Django 3.2.12 on 2024-04-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_treecategory_named_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecategory',
            name='named_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
