# Generated by Django 3.2.12 on 2024-04-12 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_treecategory_named_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.treecategory'),
        ),
    ]
